### ISSUE TITLE
Changing remote signer backend produces a panic in oasis-node

### ISSUE THREAD

**Issue by raynaudoe** [oasisprotocol/oasis-core#3002]
##### SUMMARY
Switching remote-signer's signer backend affects oasis-node stability. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
/tendermint/tendermint@v0.32.8/node/node.go

##### OASIS NODE VERSION

```
Software version: 20.6
Runtime protocol version: 0.13.0
Consensus protocol version: 0.25.0
Committee protocol version: 0.9.0
Tendermint core version: 0.33.4
ABCI library version: 0.16.2
Go toolchain version: 1.14.3

```

##### OS / ENVIRONMENT
Ubuntu 18.04
go version go1.14.3 linux/amd64

##### STEPS TO REPRODUCE
-  Run `oasis-node` with `remote-signer` as a signer for the consensus role:

```
oasis-node --config /home/ubuntu/serverdir/etc/config.yml
--signer.backend composite \
--signer.composite.backends 1:file,2:file,3:file,4:remote \
--signer.remote.address myremotesigner.com:3001  \
--signer.remote.client.certificate ./remote-signer/remote_signer_client_cert.pem \
--signer.remote.client.key ./remote-signer/remote_signer_client_key.pem \
--signer.remote.server.certificate ./remote-signer/remote_signer_server_cert.pem
```

- Run  `remote-signer`  using `file` as signer backend.
```
oasis-remote-signer --datadir ./data \
--signer file \
--client.certificate ./data/remote_signer_client_cert.pem  \
--log.level DEBUG \
--grpc.port 3001 
```

- Wait a few minutes for node to synchronize.

- Stop `oasis-node` on server.

- Delete `consensus_pub.pem` on server

- Replace `remote-signer` backend for `ledger`

- Run `remote-signer` on local machine and `oasis-node` on server

- `oasis-node` crashes after a few seconds

##### ACTUAL RESULTS

crash backtrace:

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe82422]
goroutine 1 [running]:
github.com/tendermint/tendermint/node.NewNode(0xc000340500, 0x0, 0x0, 0xc02bf0e6d0, 0x1bbb060, 0xc02bedc520, 0xc02b8d07e0, 0xc02b85ba20, 0xc02bf0c560, 0x1be7b20, ...)
	github.com/tendermint/tendermint@v0.32.8/node/node.go:625 +0x442
github.com/oasislabs/oasis-core/go/consensus/tendermint.(*tendermintService).lazyInit.func3(0xc018290a80, 0x0)
	github.com/oasislabs/oasis-core/go/consensus/tendermint/tendermint.go:1067 +0x2bf
github.com/oasislabs/oasis-core/go/consensus/tendermint.(*tendermintService).Start(0xc000102d80, 0x182b508, 0x16)
	github.com/oasislabs/oasis-core/go/consensus/tendermint/tendermint.go:252 +0x89
github.com/oasislabs/oasis-core/go/oasis-node/cmd/node.newNode(0x0, 0x0, 0x0, 0x0)
	github.com/oasislabs/oasis-core/go/oasis-node/cmd/node/node.go:761 +0x2379
github.com/oasislabs/oasis-core/go/oasis-node/cmd/node.NewNode(...)
	github.com/oasislabs/oasis-core/go/oasis-node/cmd/node/node.go:475
github.com/oasislabs/oasis-core/go/oasis-node/cmd/node.Run(0x295f980, 0xc00025e1c0, 0x0, 0xe)
	github.com/oasislabs/oasis-core/go/oasis-node/cmd/node/node.go:84 +0x40
github.com/spf13/cobra.(*Command).execute(0x295f980, 0xc00003c100, 0xe, 0xe, 0x295f980, 0xc00003c100)
	github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x295f980, 0x3f, 0x0, 0x0)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
github.com/oasislabs/oasis-core/go/oasis-node/cmd.Execute()
	github.com/oasislabs/oasis-core/go/oasis-node/cmd/root.go:45 +0x4b
main.main()
	github.com/oasislabs/oasis-core/go/oasis-node/main.go:9 +0x20
```

##### EXPECTED RESULTS

oasis-node should not have crashed

**Comment by kostko** [comment]
Can you try reproducing this using the latest master?

**Comment by raynaudoe** [comment]
With the latest code in master it doesn't get that far, it doesn't crash, though:
```
{"caller":"node.go:683","err":"initGenesis: failed to create local genesis file provider: genesis:  
malformed genesis file: address: decoding from bech32 failed: decoding bech32 failed: string not all 
lowercase or all uppercase","level":"error","module":"oasis-node","msg":"failed to initialize the 
genesis provider","ts":"2020-06-11T12:32:13.126158703Z"}
```

**Comment by kostko** [comment]
Yeah, so you can't use the same genesis file as master has breaking changes. As there is currently no testnet with the master version, you will need to generate a test genesis file with your validator nodes.

You can use the `oasis-node genesis init` command to prepare a genesis file. I can provide some more detailed instructions later.

**Comment by raynaudoe** [comment]
Great! As soon as you post those instructions I'll try again.
Thanks!

**Comment by kostko** [comment]
To prepare a local test network with a single validator node you can do the following:
* Provision your entity and node in the same way as you did for the testnet.
* Create a genesis file by running:
  ```
  oasis-node genesis init \
    --chain.id test \
    --entity /path/to/entity_genesis.json \
    --node /path/to/node_genesis.json \
    --debug.dont_blame_oasis \
    --debug.test_entity \
    --debug.allow_test_keys
  ```
  This will generate a `genesis.json` in your current working directory.
* Run the node as follows:
  ```
  oasis-node \
    --datadir /path/to/node/datadir \
    --genesis.file /path/to/genesis.json \
    --worker.registration.entity /path/to/entity.json \
    --consensus.validator \
    --debug.dont_blame_oasis \
    --debug.allow_test_keys \
    --log.level debug
  ```
  (Add any signer-specific arguments as needed.)

Note that this enables unsafe debug-only behavior, but it should be fine for your tests.

**Comment by raynaudoe** [comment]
Ok, checked, this is working ok on master!
Thanks!

**Comment by kostko** [comment]
Nice to hear!
