### ISSUE TITLE
unit test timeout failure after following build docs

### ISSUE THREAD

**Issue by joepetrakovich** [oasisprotocol/oasis-core#4348]
I've followed the documentation precisely on a new Ubuntu 20.04 VM on Azure with 8gb ram and have run into several hiccups that I think the documentation should address.

Unit tests are failing at TestFakeCapabilitySGX after running `make test-unit`

```
=== RUN   TestFakeCapabilitySGX
--- PASS: TestFakeCapabilitySGX (0.01s)
PASS
ok      github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/debug/byzantine   (cached)
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/debug/control     [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/debug/dumpdb      [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/debug/fixgenesis  [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/debug/storage     [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/debug/txsource    [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/debug/txsource/workload   [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/genesis   [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/governance        [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/ias       [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/identity  [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/identity/tendermint       [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/keymanager        [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/node      [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/registry  [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/registry/entity   [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/registry/node     [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/registry/runtime  [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/signer    [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/stake     [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/storage   [no test files]
FAIL
make[1]: *** [Makefile:89: test-node] Error 1
make[1]: Leaving directory '/home/joe/oasis-core/go'
make: *** [Makefile:98: test-unit-go] Error 2
```

The e2e tests fail as well.  This occurs when myself and some others have separately followed the documentation.  I think ideally this should go without a hitch.  My next plan is to get an IDE and bug into it, but I'm curious if this has an obvious solution.

Others have reported getting the same failure using the docker environment.

Could you recommend additional setup and configuration steps that would make these pass?

**Comment by kostko** [comment]
From the above output it is not obvious that `TestFakeCapabilitySGX` is the one that is failing. Can you provide full output?

**Comment by joepetrakovich** [comment]
> From the above output it is not obvious that `TestFakeCapabilitySGX` is the one that is failing. Can you provide full output?

Attached is everything on stdout.

[out.txt](https://github.com/oasisprotocol/oasis-core/files/7492689/out.txt)

**Comment by kostko** [comment]
Seems like the node tests are failing for you due to:

> panic: test timed out after 5m0s

Could be that tests are just running longer in your machine and so the timeout is too low. You could try increasing the timeout value by editing the makefile. If that doesn't work we can try looking into it, but tests are passing on CI and for me locally.

**Comment by Brigadirk** [comment]
I can confirm that my stdout looks the same as joepetrakovich.

```
goroutine 412614 [chan receive]:
github.com/oasisprotocol/oasis-core/go/consensus/tendermint/full.(*tendermintPubsubBuffer).writer(0xc034686de0)
        /home/joe/oasis-core/go/consensus/tendermint/full/pubsub.go:66 +0xc7
created by github.com/oasisprotocol/oasis-core/go/consensus/tendermint/full.newTendermintPubsubBuffer
        /home/joe/oasis-core/go/consensus/tendermint/full/pubsub.go:31 +0x231
FAIL    github.com/oasisprotocol/oasis-core/go/oasis-node       300.977s
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd   [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/common    [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/common/background [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/common/consensus  [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/common/context    [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/common/flags      [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/common/genesis    [no test files]
?       github.com/oasisprotocol/oasis-core/go/oasis-node/cmd/common/grpc       [no test files]
```

**Comment by joepetrakovich** [comment]
Perhaps its this timeout === RUN   TestNode/RootHash/Direct/EquivocationEvidence
panic: test timed out after 5m0s

Do I need any kind of special firewall rules/allowances?  I'll try increasing the timeout as you suggest @kostko

**Comment by kostko** [comment]
No firewall changes should be required unless you are firewalling your loopback device.

**Comment by kostko** [comment]
Oh I remember we did see some weirdness if there were no non-loopack network interfaces with an IP configured, not sure if this is still an issue.

**Comment by joepetrakovich** [comment]
I increased the timeout to 15m and it seems like it passed.   At least I dont see any errors or failures.  They just end with "make[1]: Leaving directory '/home/joe/oasis-core/go'   I assume that means we're good?

[out2.txt](https://github.com/oasisprotocol/oasis-core/files/7492734/out2.txt)

**Comment by Brigadirk** [comment]
Both of our e2e tests fail at the same point, even if we crank up the VM to exceed the system requirements by orders of magnitude. What could be the issue here? There is no timeout I can find in the Makeflile for the e2e nor is there in the .sh that it refers to.

**Comment by joepetrakovich** [comment]
here's the e2e error

```
y.pem --validator_entity /tmp/oasis-test-runner617615431/e2e/runtime/txsource-multi-short/network/entity-3/entity.pem --validator_entity /tmp/oasis-test-runner617615431/e2e/runtime/txsource-multi-short/network/entity-4/entity.pem"
ts=2021-11-09T00:22:41.906013166Z level=info module=scenario/e2e/runtime/txsource-multi-short caller=txsource.go:724 msg="starting workload" name=queries node=client-1
ts=2021-11-09T00:22:41.906658472Z level=info module=scenario/e2e/runtime/txsource-multi-short caller=txsource.go:787 msg="launching workload binary" args="debug txsource --address unix:/tmp/oasis-test-runner617615431/internal-800808049.sock --debug.allow_test_keys --datadir /tmp/oasis-test-runner617615431/e2e/runtime/txsource-multi-short/workload-queries/client-1 --debug.dont_blame_oasis --debug.test_entity --log.format JSON --log.level DEBUG --grpc.log.debug --genesis.file /tmp/oasis-test-runner617615431/e2e/runtime/txsource-multi-short/network/genesis.json --runtime.runtime_id 8000000000000000000000000000000000000000000000000000000000000000 --workload queries --time_limit 6m0s --seed 84d97e28306468cf773ed5010404d90b --gas_price 1 --queries.consensus.num_kept_versions 0 --validator_entity /tmp/oasis-test-runner617615431/e2e/runtime/txsource-multi-short/network/entity-1/entity.pem --validator_entity /tmp/oasis-test-runner617615431/e2e/runtime/txsource-multi-short/network/entity-2/entity.pem --validator_entity /tmp/oasis-test-runner617615431/e2e/runtime/txsource-multi-short/network/entity-3/entity.pem --validator_entity /tmp/oasis-test-runner617615431/e2e/runtime/txsource-multi-short/network/entity-4/entity.pem --queries.runtime.enabled=false"
level=error module=grpc/client caller=grpc.go:242 ts=2021-11-09T00:24:52.062168022Z msg="request failed" method=/oasis-core.Consensus/GetBlock req_seq=2 rsp="unsupported value type" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
ts=2021-11-09T00:24:52.068442177Z level=warn module=scenario/e2e/runtime/txsource-multi-short caller=txsource.go:700 msg="failed to query latest consensus block" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
level=error module=test-runner caller=root.go:434 ts=2021-11-09T00:24:52.136002677Z msg="failed to run scenario" err="root: failed to run scenario: oasis: compute-3 node terminated: signal: killed" scenario=e2e/runtime/txsource-multi-short run_id=0
ts=2021-11-09T00:24:52.644128184Z level=info module=scenario/e2e/runtime/txsource-multi-short caller=txsource.go:799 msg="workload finished" name=oversized node=client-0 err="exit status 1"
ts=2021-11-09T00:24:52.649948436Z level=info module=scenario/e2e/runtime/txsource-multi-short caller=txsource.go:799 msg="workload finished" name=delegation node=client-0 err="exit status 1"
ts=2021-11-09T00:24:52.87251831Z level=info module=scenario/e2e/runtime/txsource-multi-short caller=txsource.go:799 msg="workload finished" name=runtime node=client-0 err="exit status 1"
ts=2021-11-09T00:24:53.689660559Z level=info module=scenario/e2e/runtime/txsource-multi-short caller=txsource.go:799 msg="workload finished" name=governance node=client-0 err="exit status 1"
ts=2021-11-09T00:24:57.586540433Z level=info module=scenario/e2e/runtime/txsource-multi-short caller=txsource.go:799 msg="workload finished" name=registration node=client-0 err="exit status 1"
ts=2021-11-09T00:24:57.589339658Z level=info module=scenario/e2e/runtime/txsource-multi-short caller=txsource.go:799 msg="workload finished" name=commission node=client-0 err="exit status 1"
ts=2021-11-09T00:24:57.589845663Z level=info module=scenario/e2e/runtime/txsource-multi-short caller=txsource.go:799 msg="workload finished" name=parallel node=client-0 err="exit status 1"
ts=2021-11-09T00:24:57.652320817Z level=info module=scenario/e2e/runtime/txsource-multi-short caller=txsource.go:799 msg="workload finished" name=transfer node=client-0 err="exit status 1"
Error: root: failed to run scenario: root: failed to run scenario: oasis: compute-3 node terminated: signal: killed
make: *** [Makefile:104: test-e2e] Error 1
```

**Comment by joepetrakovich** [comment]
Closing since my original question was resolved.  I'm not going to worry about the e2e tests since I'm using a smaller VM.
